### ISSUE TITLE
Add color picker support

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/poll#11]
Instead of manually entering HTML-codes for colors, it would be great to have some kind of color picker. 

Now, I have commented out the first stab at this on https://github.com/backdrop-contrib/poll/blob/68c578b0f76b772483f6778b71c2b7a71c3db6c7/poll.module#L917-L921 that tries to re-use colorpicker of Color module, however I couldn't figure out how to make the `backdrop_render();` and `color_get_color_element()` functions to work together.

**Comment by docwilmot** [comment]
Dont do it in the theme function. change color field to type 'color':
```
 $form['color'] = array(
    '#type' => 'color',
    '#title' => t('Color'),
...
```

And convert all the random colors in the array to `#000000` format.

**Comment by alanmels** [comment]
Fixed with https://github.com/backdrop-contrib/poll/commit/e6c2b8c129997787d5cf03be4c245228a2d0ec23 Thank you very much @docwilmot for the hint!
