### ISSUE TITLE
cache needs to be cleared after voting

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/poll#12]
When a user votes in a poll, a different user cannot vote the same poll, as it shows as already voted, until the cache is cleared.

**Comment by robertgarrigos** [comment]
There is a line:

```
  cache('cache_entity_node')->flush();
```

just after voting (within poll_vote() function) or cancelling a vote (within poll_cancel() function), which is supposed to clear the cache, but it's not. However, cancelling a vote or voting and THEN running that function within devel 'Execute php' page, it does clear the cache and everything woks fine.

I fixed this by putting that line right at the beginning of the hook_view() function.

**Comment by alanmels** [comment]
Thanks for the finding. Your are right - it's better to expire cache at a single place when user views poll instead of trying to catch it at multiple places.

**Comment by robertgarrigos** [comment]
I need to reopen this, as it is not completely fixed. On a production site with caching set on for all pages, the user who just voted still see the unvoted poll until cache refreshed manually.

**Comment by robertgarrigos** [comment]
sorry, I saw this error again but couldn't reproduce it again.

**Comment by robertgarrigos** [comment]
yes, found the problem with the latest poll block. It needs also to flush de cache. I will add the pr.

**Comment by alanmels** [comment]
Merged on https://github.com/backdrop-contrib/poll/pull/13 Thanks! Let me know if you want to become a co-maintainer for this module.
