### ISSUE TITLE
Request to take over the maintainership of the poll module

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/poll#2]
The README file states the module is seeking maintainers. I'd like to spend some time fixing this one. Request to assign this module to me. Thanks!

**Comment by docwilmot** [comment]
Yep, go for it. One of the few I've ported for minimal use, that I no longer need (never needed after all). Thanks for offering. I believe you're meant to send a PR with you as new maintainer.

**Comment by alanmels** [comment]
> One of the few I've ported for minimal use, that I no longer need (never needed after all)

Did it work for you back then? It's not functional now.

> Thanks for offering. I believe you're meant to send a PR with you as new maintainer.

Sorry I missed that part. Just created PR.

**Comment by docwilmot** [comment]
I believe it did work, but not certain.

**Comment by alanmels** [comment]
> I believe it did work, but not certain.

I don't see any changes from my end yet. The https://github.com/backdrop-contrib/poll page is still showing "Seeking maintainers". Also I don't see any administrative rights on the module's page. You could adjust the permissions I could push this PR myself.

**Comment by alanmels** [comment]
> I believe it did work, but not certain.

Only now I see it was an answer to my question if the module worked after the initial port or not. Please review https://github.com/backdrop-contrib/poll/pull/3 and make necessary changes on permissions over the module. Thanks a lot!

**Comment by alanmels** [comment]
Just've noticed https://github.com/backdrop-contrib/poll/pull/3#issuecomment-782407242 So disregard the above request, will wait until @jenlampton or @klonos review this. Thanks.

**Comment by jenlampton** [comment]
@alanmels I have merged your PR and granted you admin rights on the repository. Thank you for taking over the poll module! 🎊
