### ISSUE TITLE
Prevent admins and privileged users from [pre]setting vote counts

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/poll#5]
I always wondered why Drupal 7's poll module allowed admins to preset vote counts. I don't see any reason other then manipulating polls. 

I would like to make this right for Backdrop's version of the module. On the other hand I took over maintaining the module just yesterday and don't want to take such bold decisions all by myself without approval of other community members. So what do you say on this?

![why-preset](https://user-images.githubusercontent.com/56604405/109108424-c7212980-76f0-11eb-959e-870c8c38883a.png)

**Comment by philsward** [comment]
My only guess for manipulation is so an admin can show offline collected polls.

Maybe part of the poll is online and part is offline, or maybe the whole poll is offline and there needs a way to record those numbers.

Outside of that, it makes sense to remove it.

**Comment by ericfg** [comment]
I can see it being useful in a strange context where the issue started in a meeting and then it was decided to put it online for the larger community; so someone would want to set the numbers based on the vote in the meeting. 

even if the goal is to manipulate the count (there could be valid reasons I guess and no one really takes anon polls seriously) why remove a feature that exists?

**Comment by klonos** [comment]
I also find this feature odd @alanmels, and cannot think of any other reason other than allowing vote manipulation as you say. If it were up to me, or if I could turn back time, I'd never add it to the module.

Having said that though, if we remove it now, we'd be causing a feature regression for existing sites, which is not good either.

**Comment by ericfg** [comment]
re: feature regression concerns: how hard would it be to hide that functionality by default but allow it if explicitly requested?

**Comment by alanmels** [comment]
Thanks for the inputs. After reading each feedback I'm now convinced we should leave it as is. Especially, Phil's argument that there could be use cases for combination of offline and online polls. Also regression concerns are legitimate. So I'm putting this idea off for now.

**Comment by philsward** [comment]
If anything, I would suggest (maybe through contrib) a way to create permissions that would allow an admin change those numbers, but not an editor. I've never used the survey module so this may already be a thing. Just thinking aloud.
